---
- name: Create /var/docker/op-connect directory
  ansible.builtin.file:
    dest: /var/docker/op-connect
    state: directory
    mode: 0755

- name: Copy Docker Compose file
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /var/docker/op-connect/docker-compose.yml
    mode: 0640

- name: Create 1Password credentials file env variables file
  ansible.builtin.template:
    src: "{{ credentials_file }}"
    dest: /var/docker/op-connect/1password-credentials.json
    mode: 0640

- name: Start the 1Password Connect containers
  community.docker.docker_compose:
    project_src: /var/docker/op-connect
    state: present
    pull: yes
