---
- name: Create /var/docker/op-connect directory
  ansible.builtin.file:
    dest: /var/docker/1password-connect
    state: directory
    mode: 0755

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.j2
    dest: /var/docker/1password-connect/docker-compose.yml
    mode: 0640

- name: Create 1Password credentials file env variables file
  ansible.builtin.template:
    src: "{{ 1password_credentials_file }}"
    dest: /var/docker/1password-connect/1password-credentials.json
    mode: 0644

- name: Start the 1Password Connect containers
  community.docker.docker_compose_v2:
    project_src: /var/docker/1password-connect
    state: present
    pull: always
    build: always
    recreate: always
